version: '3.7'

services:
    app:
        build: proxy
        restart: ${RESTART:-no}
        ports: 
            - "${HOST_PORT}80"
        volumes: 
            - ./app:/app
        environment:
            VIRTUAL_HOST: srfunilariaepintura.com
            VIRTUAL_HOST_ALIAS: srfunilariaepintura.com
            LETSENCRYPT_HOST: srfunilariaepintura.com
            LETSENCRYPT_EMAIL: matheus_vilela@icloud.com
        networks:
            - nginx-gateway

networks:
    nginx-gateway:
        external:
            name: nginx-gateway